spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      ssl.endpoint.identification.algorithm:
server:
  port: 9090